# 当用户数达到以下值时，之后的注册都需要邀请码
sign_in_limit_without_invitation: 5000

# 帖子标题的最小长度
post_title_min: 10
# 帖子标题的最大长度
post_title_max: 80
# 帖子内容的最小长度
post_content_min: 30
# 回复内容的最小长度
comment_content_min: 10

# 点击首页 所有热门 下的 高收藏 时，只显示收藏数大于以下值的帖子
collectors_limit: 0
# 点击首页 所有热门 下的 高赞同 时，只显示赞同数大于以下值的帖子
up_voters_limit: 0
# 点击首页 所有热门 下的 高回复 时，只显示总回复数大于以下值的帖子
total_comments_limit: 0

# will_paginate 每页显示的数量
per_page: 20
