# 新帐号奖励
new_account: 50
# 每天登录奖励
normal_day_sign_in: 2
# 月初登录奖励
first_month_day_sign_in: 30

# 技术无关节点发帖消耗
non_technical_post: -2
# 儿童节点发帖奖励
children_post: 10
# 删除帖子消耗
delete_post: -8

# 当帖子或回复被删除后，所有的子回复也将被系统一并删除，这些子回复的作者将得到积分补偿
commenter_compensation: 1
# 当帖子或回复被删除后，与之相关的赞同也将被系统一并删除，这些赞同者将得到积分补偿
up_voter_compensation: 2
# 当帖子或回复被删除后，与之相关的反对也将被系统一并删除，这些反对者将得到积分补偿
down_voter_compensation: 2
# 当帖子被删除后，与之相关的收藏也将被系统一并删除，这些收藏者将得到积分补偿
collector_compensation: 4

# 回复消耗
comment: -1
# 删除回复消耗
delete_comment: -4
# 赞同消耗
vote_up: -2
# 被赞同奖励
be_voted_up: 1
# 反对消耗
vote_down: -2
# 收藏消耗
collect: -4
# 被收藏奖励
be_collected: 2
# 关注消耗
follow: -8
# 被关注奖励
be_followed: 4
# B未关注A，A给B发私信，A所需的消耗
send_secret: -8
# B未关注A，A给B发私信，B所得的补偿
received_secret: 4
# B已关注A，A给B发私信，A不会消耗积分，B也不会被补偿积分

# 邀请消耗
invite: -16

# 达到奖励级别1，所需的数量
level_1_number: 25
# 达到奖励级别2，所需的数量
level_2_number: 50
# 达到奖励级别3，所需的数量
level_3_number: 100

# 被收藏数达到奖励级别1，所另外奖励的积分数量
be_collected_level_1_points: 20
# 被收藏数达到奖励级别2，所另外奖励的积分数量
be_collected_level_2_points: 40
# 被收藏数达到奖励级别3，所另外奖励的积分数量
be_collected_level_3_points: 60

# 被赞同数达到奖励级别1，所另外奖励的积分数量
be_voted_up_level_1_points: 10
# 被赞同数达到奖励级别2，所另外奖励的积分数量
be_voted_up_level_2_points: 20
# 被赞同数达到奖励级别3，所另外奖励的积分数量
be_voted_up_level_3_points: 30

# 当被收藏数大于以下值时，帖子被认为是好帖，系统将其设置为不可删除
valuable_limit_for_collecting: 15
# 当被赞同数大于以下值时，帖子被认为是好帖，系统将其设置为不可删除
valuable_limit_for_voting_up: 30
